[theme]
base = "light"
primaryColor = "#0077C8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FB"
textColor = "#1B1B2F"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
