[theme]
base = "light"
primaryColor = "#170F5F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF1FB"
textColor = "#1B1B2F"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
